### ISSUE TITLE
Support search_after to use if for getting documents after and before a given document

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit-datasource#12]
The `search_after` feature is now available in Quickwit. 

We can now use it to implement the [log context feature](https://grafana.com/docs/grafana/latest/explore/logs-integration/#log-context) of the explore view.

Code pointers:
- [get log row context function in elasticsearch plugin](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/elasticsearch/datasource.ts#L504C3-L524)
- [makeLogContextDataRequest in elasticsearch plugin](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/elasticsearch/datasource.ts#L1038-L1081)

**Comment by idrissneumann** [comment]
Here's a pull request: https://github.com/quickwit-oss/quickwit-datasource/pull/23

Seems working fine:

<img width="1192" alt="Screenshot 2023-11-22 at 15 00 56" src="https://github.com/quickwit-oss/quickwit-datasource/assets/12884347/329bd216-4f13-4c0d-84a8-6271e6711ed4">

And in the logs:

```
grafana-quickwit-datasource  | logger=plugin.quickwit-quickwit-datasource t=2023-11-22T14:00:50.030529999Z level=info msg="Executing multisearch" searchrequests="[map[query:map[bool:map[filter:map[range:map[timestamp:map[gte:2023-11-22T06:25:46Z lte:2023-11-22T13:25:46Z]]]]] search_after:[1.700659546e+12] size:50 sort:[map[timestamp:map[order:desc]]]]]"
``
