### ISSUE TITLE
Wildcard in a text box escapes the wildcard

### ISSUE THREAD

**Issue by mzupan** [quickwit-oss/quickwit-datasource#130]
Using the plugin, if I set a textbox variable and use a wildcard like

<img width="340" alt="Screenshot 2024-06-09 at 9 38 10 AM" src="https://github.com/quickwit-oss/quickwit-datasource/assets/205373/a2e051dc-49ec-445c-85f7-631f81825f1a">

In the query it is escaping the `*`. Here is the query it sent to quickwit

```
query:"status_code:[200 TO 499] AND endpoint:\"\\*\""
```

This is my query for the graph

```
status_code:[200 TO 499] AND endpoint:"$endpoint"
```

Also tried

```
status_code:[200 TO 499] AND endpoint:$endpoint
status_code:[200 TO 499] AND endpoint:""$endpoint
```

**Comment by uptickmetachu** [comment]
everything is escaped when sent via query it seems.

This severely limits the use of variables as a way to drill down for search.

**Comment by fmassot** [comment]
@mzupan @uptickmetachu I think it's possible to avoid this pb. On Fly.io we have a query text box, and this works: `${query:text}`

To give you the full query run on Fly: `fly.app.name:${app:singlequote} fly.app.instance:${instance:singlequote} ${query:text}`

**Comment by uptickmetachu** [comment]
Yup works for me!

I do have to use some querybuilding trickery to make it work as a multivalue `*` when nothing is selected and as a quoted text for when a value is selected.
