### ISSUE TITLE
datasource not available after installing the plugin

### ISSUE THREAD

**Issue by nbari** [quickwit-oss/quickwit-datasource#134]
I am installing the plugin using:
    
    grafana-cli plugins install quickwit-quickwit-datasource

The plugin seems to be  installed:
```sh
# grafana-cli plugins ls
installed plugins:
quickwit-quickwit-datasource @ 0.4.5
```
I restart grafana , stop/start but I can't get the data source for Quickwit, any ideas about how to install it on a local grafana (`grafana version 11.1.4`)

**Comment by nbari** [comment]
` chown -R grafana:grafana plugins` fixed the problem

**Comment by fmassot** [comment]
thanks @nbari for the follow-up!
