### ISSUE TITLE
Add dynamic fields in the list of available field in aggregation query editor

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit-datasource#20]
When forging an aggregation query, we need to choose the fields to aggregate on. Currently, the list of proposed fields is limited to fields available in the index doc mapping. But, in the case of a dynamic mapping, this means that most of the fields can be missed. Instead of using the doc mapping to get the list of available fields, we should use the field capabilities endpoint of Quickwit when it will be added.

Endpoint to use: `_elastic/{index-id}/_field_caps`
Docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-caps.html

**Comment by idrissneumann** [comment]
![Image](https://github.com/quickwit-oss/quickwit-datasource/assets/12884347/6a004cc9-4d2f-47b2-9977-75e6026c1733)

* `Aggregable fields: true` for the second group by field.
* `Date histogram`: filter on type `datetime`

**Comment by idrissneumann** [comment]
```shell
curl http://localhost:7280/api/v1/_elastic/otel-traces-v0_6/_field_caps
```

**Comment by idrissneumann** [comment]
PR's here: https://github.com/quickwit-oss/quickwit-datasource/pull/41
