### ISSUE TITLE
Display Quickwit 4XX response body in the grafana UI

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit-datasource#28]
Currently, if Quickwit returns a 4XX, the plugin backend does not handle properly the response and the user has no feedback on the error. 
We should display the error in the Grafana UI.

**Comment by idrissneumann** [comment]
Work in progress in this PR: https://github.com/quickwit-oss/quickwit-datasource/pull/31

**Comment by fmassot** [comment]
Closed by #31
