### ISSUE TITLE
Failed to load log volume for this query

### ISSUE THREAD

**Issue by kfirfer** [quickwit-oss/quickwit-datasource#39]
Hello

Im not sure if its grafana / quickwit plugin,
we are getting this error around 50% of the times:

```
Failed to load log volume for this query
Internal error: `Aborting aggregation because memory limit was exceeded. Limit: 500.00 MB, Current: 1.36 PB`.
```

Grafana version: 10.2.2
Quickwit datasource plugin version: 0.2.4

image for reference
![Screenshot from 2023-12-20 21-09-46](https://github.com/quickwit-oss/quickwit-datasource/assets/7741545/b484b8e0-d97c-4c58-a5cc-331278a8962d)
:

**Comment by fmassot** [comment]
@kfirfer, this is indeed a bug in Quickwit 0.6. This is fixed in the main branch or docker edge version.
0.7 should be release pretty soon.

**Comment by kfirfer** [comment]
@fmassot i upgraded to 0.3 and i didnt encountered it anymore
thanks alot !
