### ISSUE TITLE
Improve UX when defining an index with its timestamp field and output format

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit-datasource#4]
The UI should validate the output format and we should autofill the input by calling retrieving the output format on quickwit API.

**Comment by idrissneumann** [comment]
Use the describe endpoint

<img width="659" alt="Screenshot 2023-12-08 at 14 48 55" src="https://github.com/quickwit-oss/quickwit-datasource/assets/12884347/09c22855-b1ca-4f42-ae91-8a1bebb3e9c6">

**Comment by idrissneumann** [comment]
PR's here: https://github.com/quickwit-oss/quickwit-datasource/pull/38

**Comment by fmassot** [comment]
Fixed
