### ISSUE TITLE
Support Grafana tracing view(s)

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit-datasource#5]
To support the Jaeger grafana plugin without the jaeger-query layer, we need to implement the following REST endpoints:

- `GET api/services`
- `GET api/services/{service}/operations`
- `GET api/traces?service={service}&start={start_in_ns}&end={end_in_ns}&lookback=custom`
- `GET api/traces/{trace-id-base-64}`

The handlers of those endpoints should use the [jaeger gRPC service](https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-jaeger/src/lib.rs#L453).

**Comment by macthestack** [comment]
This would be great if possible!

In https://quickwit.io/blog/observing-rust-app-with-quickwit-jaeger-grafana it sure looks like someone's got it working.

**Comment by fmassot** [comment]
@macthestack I wrote this :)

We could make Quickwit compatible with the Jaeger grafana plugin. From the [plugin code](https://github.com/grafana/grafana/blob/ffcaef9c17f55ad98690d70bb5953e1131361729/public/app/plugins/datasource/jaeger/datasource.ts#L136-L147), a Jaeger internal API is used `api/traces` instead of the gRPC API.  We could either expose this API in Quickwit or just copy the frontend code of the Jaeger plugin and do the gRPC calls on the Quickwit backend plugin.

Note that tempo offers richer views ([Service Graph and Service Graph view](https://grafana.com/docs/grafana/latest/datasources/tempo/service-graph/)) and it could be nice to add that too in the plugin.

-

**Comment by etolbakov** [comment]
@fmassot I believe we can close this one right?

**Comment by fmassot** [comment]
Yes indeed!
