### ISSUE TITLE
default fields inexistent in trace

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit-datasource#67]
By default, when searching traces in grafana, the default field is not set.

We have some relevant field we should be able to search into.
span_name for instance, but also event_names, which is a tokenized name that is not even visible from the user without looking into our source code.

**Comment by fmassot** [comment]
@fulmicoton I fixed it in Quickwit. https://github.com/quickwit-oss/quickwit/pull/4602
