### ISSUE TITLE
Keeps refreshing output while typing query

### ISSUE THREAD

**Issue by damyan90** [quickwit-oss/quickwit-datasource#70]
It's pretty annoying behaviour. I suppose it's coming from the datasource and not Grafana - correct me please if I'm wrong.

Expectation would be to not reload anything automatically. There are often situtation where you have a log entry open and checking some fields and their values and only then want to construct the whole query. 
If it keeps running in the meantime the "preview" of particular log is gone.

EDIT:
Plugin version: v0.4.0 / v0.3.2
quickwit: 0.7.1

**Comment by silentsokolov** [comment]
I completely agree. It would be great if we could completely disable automatic updates when entering a query and only initiate them manually. With large volumes logs, these unnecessary queries and waiting times can become burdensome.

Plugin version: v0.4.0-beta.0 / v0.3.2
quickwit: 0.7.1

**Comment by fmassot** [comment]
Good point. I’m in favor of changing the behavior. @ddelemeny your opinion?

**Comment by ddelemeny** [comment]
Agreed. Triggering unwanted queries is a waste of resources, let's change that.
