### ISSUE TITLE
Unknown field `end_timestamp`

### ISSUE THREAD

**Issue by silentsokolov** [quickwit-oss/quickwit-datasource#87]
On the Explore page

v0.4.0-beta.1
```
/api/datasources/uid/<>/resources/_elastic/<>/_field_caps?start_timestamp=1708489939&end_timestamp=1708511540
```
```json
{
  "indices": [
    "<>"
  ],
  "fields": {
     DATA
  },
}
```

v0.4.0-beta.4
```
/api/datasources/uid/<>/resources/_elastic/<>/_field_caps?start_timestamp=1708489939&end_timestamp=1708511540
```

```json
{
  "message": "unknown field `end_timestamp`, expected one of `allow_no_indices`, `expand_wildcards`, `fields`, `ignore_unavailable`"
}
```

quickwit: 0.7.1

**Comment by silentsokolov** [comment]
Ok, I see https://github.com/quickwit-oss/quickwit/pull/4547

**Comment by silentsokolov** [comment]
Reviving the issue. I understand that the beta version of the plugin is just that, a beta, but it has fixed a lot of critical bugs. I would like to use the beta version specifically. 

Perhaps it's worth adding the quickwit version to the settings so that both the edge and stable versions can be used.

**Comment by fmassot** [comment]
@silentsokolov we are going to release very very soon a new Quickwit version (0.8) with a new plugin version 0.4.
