### ISSUE TITLE
Add sort direction

### ISSUE THREAD

**Issue by silentsokolov** [quickwit-oss/quickwit-datasource#89]
Sometimes, there's a need to change the sorting direction (timestamp only). Unfortunately, the defalut options available in the Grafana interface may not allow for changing the sorting direction.
Could we consider adding a special option for that?

<img width="200" alt="image" src="https://github.com/quickwit-oss/quickwit-datasource/assets/398939/0b4a66de-174e-4f83-8332-adcb0fd234e3">

**Comment by ddelemeny** [comment]
AFAICT, grafana handles sorting on the timestamp.
In Explore : 
![image](https://github.com/quickwit-oss/quickwit-datasource/assets/1690574/2789314e-0858-439e-aceb-15ac49bb33a9)

And in dashboard panels:
![image](https://github.com/quickwit-oss/quickwit-datasource/assets/1690574/1b42948f-4cf3-46f1-bed3-74e796b43144)

Does it suit your need ?

**Comment by silentsokolov** [comment]
Yes, the "Display results" option sorts the data, but only those that have been retrieved (let's say, for example, 100 rows). It would be preferable to sort at the query stage.
I'm referring only to the Explore page.

**Comment by ddelemeny** [comment]
I see. Can you please give more details about your use case ?

Issue #88 is meant to explore the quirks and shortcomings of log exploration regarding pagination, sorting and query limits. I just opened it so it's not very fleshed out at the moment but do you think your use-case would fit under that umbrella ?
