### ISSUE TITLE
Support datasource config jsonData: {oauthPassThru: true}

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit-datasource#92]
See https://grafana.com/developers/plugin-tools/create-a-plugin/extend-a-plugin/add-authentication-for-data-source-plugins#forward-oauth-identity-for-the-logged-in-user

I made this commit in the hope of fixing this issue: https://github.com/quickwit-oss/quickwit-datasource/commit/aea564e8d5b76b65f88fbcfc1c554d70fee816ed

But that's probably wishful thinking.

**Comment by ddelemeny** [comment]
Tested on grafana 10.3 : OK

**Comment by ddelemeny** [comment]
@fmassot is there still something to do here ?
