### ISSUE TITLE
Remove `AND` on a positive filter in explore view and use simple quotes

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit-datasource#98]
In the explore view, it is possible to filter on a field value by clicking on the magnifying glass.

When filtering, we add the string ` AND field:"value"`  to the query. 

Instead, with should add the string ` field:'value'` to the query and `AND` is the default operator and single quote works even on fields where positions are not stored.

**Comment by ddelemeny** [comment]
Single quoted terms aren't friendly to the lucene parser either... Do we target fixing the whole bunch of parser issues for 0.5 ?

**Comment by fmassot** [comment]
I see, we can at least remove the AND. The PR which fixes some issues on the QL will be soon merged, hopefully tomorrow.
